### ISSUE TITLE
Hotfix for importing Google font in Footer CSS stylesheet

### ISSUE THREAD

**Issue by nathanbaleeta** [unicef/iogt-pwa#11]
**Describe the bug**
Importing the google font at the top of the CSS stylesheet of the footer causes a `CssSyntaxError` and thus build process fails.

**To Reproduce**
1. `git clone https://github.com/unicef/iogt-pwa.git`
2. `cd iogt-pwa/frontend`
3. `yarn install`
4. `yarn run build`

**Expected behavior**
Build process should be successful when you run `yarn run build`

**Screenshots**
![Screenshot from 2020-10-01 14-30-50](https://user-images.githubusercontent.com/8824104/94804060-e68e8180-03f2-11eb-9916-d598178b1f17.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version: 85.0

**Additional context**
To enable successful build, had to comment out the css google font on the first line:
https://github.com/unicef/iogt-pwa/blob/develop/frontend/src/components/footer/style.css

**Steps to fix it**
- [ ]  Create a new branch from `develop` called `hotfix-import-google-font-footer`. Hint: `git checkout -b <new-branch> <existing-branch>`
- [ ]  Debug and try using external stylesheets instead of internal stylesheets
- [ ]  Verify everything is working by running `yarn run build` before pushing changes to github.
- [ ]  Commit the changes (as a single commit).
- [ ]  Push changes to github. Hint: `git push --set-upstream origin hotfix-import-google-font-footer`
- [ ]  Open a pull-request.

**Comment by harshiniwho** [comment]
> /take

Shall try to fix this! I guess it is the external reference not being parsed correctly for some reason.

**Comment by harshiniwho** [comment]
https://github.com/unicef/iogt-pwa/pull/12

I seem to be unable to request review but linking the PR here

**Comment by nathanbaleeta** [comment]
> #12
> 
> I seem to be unable to request review but linking the PR here

Creating a new branch off `develop` should be enough to help you raise a pull request once you have made any changes.
