### ISSUE TITLE
Modify Preact frontend to use Typescript

### ISSUE THREAD

**Issue by michaelclapham** [unicef/iogt-pwa#26]
Modify the frontend to use Typescript.

This can be easiest achieved by creating a new project using preact-cli's typescript template then copying over the components. 
https://preactjs.com/guide/v10/typescript/

However the exact approach is up to the implementers.

**Comment by jtoaha** [comment]
Hi Michael. I was about to add Lawrence and Arjun to this ticket but realized they don't have access yet. Is it possible to add them
@law-lin and @QuantumArjun

Also just in general for fellow people working on V3, it seems they don't have access yet, is it possible to add Riya and Sett as well? 
@riyv @settnaing199

Thank you so much.
