### ISSUE TITLE
Convert all line endings to LF

### ISSUE THREAD

**Issue by law-lin** [unicef/iogt-pwa#34]
Currently, some files are using CRLF line endings, such as `node_modules/preact-cli/lib/index.js`.

We should convert all line endings to LF.

**Comment by isedwards** [comment]
It's very easy for line endings to get mixed up on projects were we're using different operating systems - or in the case where everyone is using Windows, but the server we deploy to is using Linux.

`git` is supposed to be able to handle this for us with some changes to the *.gitattributes* settings file in the root of the repository.  Could you take a look and see whether the instructions make sense?

https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings

**Comment by isedwards** [comment]
`* text eol=lf` was added to `.gitattributes` in [c822d33](https://github.com/unicef/iogt-pwa/commit/c822d33d8c09c3ba4870ddda0de882bfddb5e725)
