### ISSUE TITLE
On smartphone view, create an article page (e.g. the "Talking about COVID-19" page is not clickable right now)

### ISSUE THREAD

**Issue by isabelzwang** [unicef/iogt-pwa#48]

**Comment by usodhi** [comment]
@isabelzwang do we want underlines on the articles (indicating a link) or not (for smartphone view or otherwise)?

**Comment by isabelzwang** [comment]
I don't think so right now, since the boxes in the design should indicate that the title is clickable, but we can definitely bring this up in the meeting!
