### ISSUE TITLE
Make sure the whole article box on the home page is clickable, not just the image and title, and try to have the article title fade to gray on hover if possible!

### ISSUE THREAD

**Issue by isabelzwang** [unicef/iogt-pwa#59]

**Comment by usodhi** [comment]
It may be confusing for the user to click on the subheadings and not have it go to that list of articles - do we just want the image + title + space in between to be clickable instead?

**Comment by isabelzwang** [comment]
Yes! We should be removing the author and date from the home page, per Laurie’s request. The reason to remove the date is because some articles don’t get updated by the country office very often, but we would still want users to be interested in the material. And, just generally, those items are not necessary on the home page featuring all of our articles and their categories, so they just take up space!

**Comment by isabelzwang** [comment]
Yes! We should be removing the author and date from the home page, per Laurie’s request. The reason to remove the date is because some articles don’t get updated by the country office very often, but we would still want users to be interested in the material. And, just generally, those items are not necessary on the home page featuring all of our articles and their categories, so they just take up space!
