### ISSUE TITLE
Design how large graphic banners should look on the mobile and tablet wireframes; brainstorm for desktop if you have time

### ISSUE THREAD

**Issue by isabelzwang** [unicef/iogt-pwa#65]

**Comment by kngoledge** [comment]
- banner for smart phone is accessible under the frame "Updated 4.20.21" and page: Walk Through Prototype (Mobile with New Nav)
- banner for feature phone is accessible under the frame "Updated 4.20.21" and page: Walk Through Prototype (Feature Phone)
- banner for feature phone is accessible under the frame "Updated 4.20.21" and page: Walk Through Prototype (Tablet)
- banner for feature phone is accessible under the frame "Updated 4.20.21" and page: Walk Through Prototype (Desktop)
